### ISSUE TITLE
Dinner -> Lunch

### ISSUE THREAD

**Issue by aeantipov** [SimonsSchool/tutorial#2]
I want to have lunch, not dinner. And you should too.

**Comment by aeantipov** [comment]
sorry, no

**Comment by SimonsSchool** [comment]
That is unreasonable, please send your log, and your CMake cache

**Comment by aeantipov** [comment]
Ok, how about this 
https://gist.github.com/aeantipov/685d178981dd5e4c6bf21ad944497f36

**Comment by SimonsSchool** [comment]
Now that's reasonable
